const YoutubeApi = [
    {
        id:1,
        iFrame: <iframe className='md:h-[20rem] md:w-[40rem]' src="https://www.youtube.com/embed/Evz_X2TW7UA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
    {
        id:2,
        iFrame : <iframe className='md:h-[20rem] md:w-[40rem]' src="https://www.youtube.com/embed/pinP23-JcyA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus .",
    },
    {
        id:3,
        iFrame : <iframe className='md:h-[20rem] md:w-[40rem]' src="https://www.youtube.com/embed/3kcniMo-fV8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
    {
        id:4,
        iFrame : <iframe width="560" height="315" src="https://www.youtube.com/embed/OM5zQJGeJGQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
    {
        id:5,
        iFrame : <iframe width="560" height="315" src="https://www.youtube.com/embed/Pm1UsqyUprg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
    {
        id:6,
        iFrame : <iframe width="560" height="315" src="https://www.youtube.com/embed/0EY1vYOC2hg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
    {
        id:7,
        iFrame : <iframe width="560" height="315" src="https://www.youtube.com/embed/_qKCV7GhS8o" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
    {
        id:8,
        iFrame : <iframe width="560" height="315" src="https://www.youtube.com/embed/6q5o7SVUKm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
    {
        id:9,
        iFrame : <iframe width="560" height="315" src="https://www.youtube.com/embed/SexnYsHiXv0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
    {
        id:10,
        iFrame : <iframe width="560" height="315" src="https://www.youtube.com/embed/I0woqpRPYwg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>,
        Code : "facere aliquid ipsum ea possimus perferendis qui ratione minima non, debitis est, nisi corporis, numquam eos id. Amet nulla quo vitae doloribus laborum impedit nihil praesentium hic ab, voluptates earum recusandae. Delectus perspiciatis ipsum consequuntur porro ea dolor amet ducimus inventore fugiat incidunt iste, voluptates quasi labore itaque accusantium, reiciendis magnam quidem nihil adipisci sunt culpa! Quas cum eius tempore repudiandae necessitatibus inventore molestias aperiam ab saepe provident cupiditate, impedit fugiat nemo magnam recusandae reprehenderit similique dolores eligendi aspernatur pariatur tempora deserunt deleniti! Nesciunt animi a mollitia maxime? Enim dolores, consequatur voluptate impedit laudantium odio reiciendis sit quasi nemo sequi voluptatibus fugit possimus labore nobis? Quisquam iure nisi nihil ratione suscipit architecto numquam vero earum nostrum, soluta culpa porro quas maxime praesentium recusandae distinctio repellendus? Doloremque quas, quaerat sunt perferendis harum iure quasi inventore, alias omnis ab itaque molestias dolore ratione totam nam. Rerum, perferendis totam.",
    },
]
export default YoutubeApi